### ISSUE TITLE
Stopped working.

### ISSUE THREAD

**Issue by JayHoltslander** [gdelmas/GithubTower#2]
Links are no longer opening in Tower and are back to opening in GitHub Desktop app

**Comment by briantully** [comment]
This is due to a recent change with Github Desktop. It looks like it was recently rebuilt as an "Electron" app, and in doing so they changed the URL scheme from "github-mac://" to "x-github-client://" which will either open the new Github Desktop (if you've downloaded it) or do nothing at all.

I have a pull request to update the extension to look for the new "x-github-client://" href and change it back to "github-mac://". 

You can find the pull request here: https://github.com/gdelmas/GithubTower/pull/3 in case you want to update it yourself rather than wait for the original author to merge it.

**Comment by gdelmas** [comment]
sadly the case was a little more complex. the scheme depends on the version of the desktop app you run. see: https://github.com/gdelmas/GithubTower#rationale
